# Log Forwarder (Fluent Bit) DaemonSet to tail log files.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: stackdriver-log-forwarder
  namespace: stackdriver-agents
  labels:
    app: stackdriver-log-forwarder
spec:
  selector:
    matchLabels:
      app: stackdriver-log-forwarder
  template:
    metadata:
      labels:
        app: stackdriver-log-forwarder
    spec:
      containers:
      - name: stackdriver-log-forwarder
        image: fluent/fluent-bit:1.0.4
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: stackdriver-log-forwarder-config
          mountPath: /fluent-bit/etc/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccountName: stackdriver-log-forwarder
      terminationGracePeriodSeconds: 60
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: stackdriver-log-forwarder-config
        configMap:
          name: stackdriver-log-forwarder-config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
# Log Forwarder (Fluent Bit) configuration map.
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackdriver-log-forwarder-config
  namespace: stackdriver-agents
  labels:
    app: stackdriver-log-forwarder
data:
  # Configuration files for service, input, filter, and output plugins.
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        # https://docs.fluentbit.io/manual/service
        Flush         1
        Log_Level     warn
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-containers.conf
    @INCLUDE input-systemd.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-fluentd.conf

  input-containers.conf: |
    [INPUT]
        # https://docs.fluentbit.io/manual/input/tail
        Name               tail
        Tag                k8s_container.*
        Path               /var/log/containers/*.log
        Parser             docker
        DB                 /var/log/fluent-bit-k8s-container.db
        Buffer_Chunk_Size  512KB
        Buffer_Max_Size    5M
        Rotate_Wait        30
        Mem_Buf_Limit      30MB
        Skip_Long_Lines    On
        Refresh_Interval   10

  input-systemd.conf: |
    [INPUT]
        Name            systemd
        Tag             docker
        Path            /var/log/journal
        DB              /var/log/fluent-bit-k8s-node-journald-docker.db
        Systemd_Filter  _SYSTEMD_UNIT=docker.service

    [INPUT]
        Name            systemd
        Tag             kubelet
        Path            /var/log/journal
        DB              /var/log/fluent-bit-k8s-node-journald-kubelet.db
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service

    [INPUT]
        Name            systemd
        Tag             node-journal
        Path            /var/log/journal
        DB              /var/log/fluent-bit-k8s-node-journald.db

    [FILTER]
        Name     grep
        Match    node-journal
        Exclude  _SYSTEMD_UNIT ^(docker|kubelet)\.service$

    [FILTER]
        Name    record_modifier
        Match   docker
        Record  logging.googleapis.com/local_resource_id k8s_node.${HOSTNAME}

    [FILTER]
        Name    record_modifier
        Match   kubelet
        Record  logging.googleapis.com/local_resource_id k8s_node.${HOSTNAME}

    [FILTER]
        Name    record_modifier
        Match   node-journal
        Record  logging.googleapis.com/local_resource_id k8s_node.${HOSTNAME}

  filter-kubernetes.conf: |
    [FILTER]
        # https://docs.fluentbit.io/manual/filter/kubernetes
        Name                kubernetes
        Match               k8s_container.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Annotations         Off

  output-fluentd.conf: |
    [OUTPUT]
        # https://docs.fluentbit.io/manual/input/forward
        Name  forward
        Match *
        Host  ${FLUENTD_IN_FORWARD_SERVICE_HOST}
        Port  ${FLUENTD_IN_FORWARD_SERVICE_PORT}

  parsers.conf: |
    [PARSER]
        # https://docs.fluentbit.io/manual/parser/json
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   json       log   do_next
        Decode_Field_As   escaped    log
