# How to apply this YAML file:
# $ kubectl apply -f rbac-setup.yaml --as=admin --as-group=system:masters
#
# Namespace for Stackdriver Agents related components.
apiVersion: v1
kind: Namespace
metadata:
  name: stackdriver-agents
---
# Config map for setting GOOGLE_APPLICATION_CREDENTIALS.
apiVersion: v1
data:
  credentials_path: ""
kind: ConfigMap
metadata:
  name: google-cloud-config
  namespace: stackdriver-agents
---
# Config map for setting CLUSTER_NAME and CLUSTER_LOCATION env vars.
apiVersion: v1
data:
  cluster_name: ""
  cluster_location: ""
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: stackdriver-agents
---
# Service account for Metadata Agent.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-agent
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Metadata Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:metadata-agent
  namespace: stackdriver-agents
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - watch
  - get
  - list
---
# ClusterRoleBinding for Metadata Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:metadata-agent
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:metadata-agent
subjects:
- kind: ServiceAccount
  name: metadata-agent
  namespace: stackdriver-agents
---
# Service account for Fluentbit Logging Agent forwarder.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stackdriver-log-forwarder
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Logging Agent Fluentbit forwarder.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:log-forwarder
  namespace: stackdriver-agents
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - watch
  - get
  - list
---
# ClusterRoleBinding for Logging Agent Fluent-bit forwarder.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:log-forwarder
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:log-forwarder
subjects:
- kind: ServiceAccount
  name: stackdriver-log-forwarder
  namespace: stackdriver-agents
---
# Service to expose in_forward plugin port on the Fluentd aggregator side.
kind: Service
apiVersion: v1
metadata:
  name: fluentd-in-forward
  namespace: stackdriver-agents
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "fluentd-in-forward"
spec:
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
  selector:
    app: stackdriver-log-aggregator
---
# Service account for Heapster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:heapster
  namespace: stackdriver-agents
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
# ClusterRoleBinding for Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:heapster
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: stackdriver-agents
