# How to apply this YAML file:
# $ kubectl apply -f rbac-setup.yaml --as=admin --as-group=system:masters
#
# Namespace for Stackdriver Agents related components.
apiVersion: v1
kind: Namespace
metadata:
  name: stackdriver-agents
---
# Config map for setting GOOGLE_APPLICATION_CREDENTIALS.
apiVersion: v1
data:
  credentials_path: ""
kind: ConfigMap
metadata:
  name: google-cloud-config
  namespace: stackdriver-agents
---
# Config map for setting CLUSTER_NAME and CLUSTER_LOCATION env vars.
apiVersion: v1
data:
  cluster_name: ""
  cluster_location: ""
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: stackdriver-agents
---
# Service account for Metadata Agent.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-agent
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Metadata Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:metadata-agent
  namespace: stackdriver-agents
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - watch
  - get
  - list
---
# ClusterRoleBinding for Metadata Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:metadata-agent
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:metadata-agent
subjects:
- kind: ServiceAccount
  name: metadata-agent
  namespace: stackdriver-agents
---
# Service account for Logging Agent.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-agent
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Logging Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:logging-agent
  namespace: stackdriver-agents
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - watch
  - get
  - list
---
# ClusterRoleBinding for Logging Agent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:logging-agent
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:logging-agent
subjects:
- kind: ServiceAccount
  name: logging-agent
  namespace: stackdriver-agents
---
# Service account for Heapster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: stackdriver-agents
---
# ClusterRole with permissions required by Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackdriver-user:heapster
  namespace: stackdriver-agents
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
# ClusterRoleBinding for Heapster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stackdriver-user:heapster
  namespace: stackdriver-agents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stackdriver-user:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: stackdriver-agents
